[package]
name = "raymarch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.9.0"
glam = "0.23.0"
pixels = "0.11.0"
winit = "0.28.3"
winit_input_helper = "0.14.0"
